"""Signal 1: LLM classifier using Groq (openai/gpt-oss-120b).

Returns an AI probability in [0.02, 0.98]. Never raises; on any failure the
signal is reported as unavailable so the request can still complete.
"""

import json
import os

from groq import Groq

MODEL = "openai/gpt-oss-120b"
TIMEOUT_SECONDS = 15
MAX_WORDS = 3000
MIN_PROB = 0.02
MAX_PROB = 0.98

SYSTEM_PROMPT = """You are an AI-text detector. Estimate the probability that the text you are given was generated by an AI language model rather than written by a person.

Consider:
- Generic, hedged, or overly balanced phrasing
- Formulaic structure (intro, three points, conclusion) and tidy transitions
- Lack of concrete personal detail, specific memories, or idiosyncratic voice
- Emotional flatness or polished but impersonal tone
- Vocabulary common in AI output ("delve", "tapestry", "it is important to note", "in today's fast-paced world")

Human writing tends to have uneven rhythm, fragments, specific details, quirks, and occasional errors.

Use the full scale:
- 0.85-0.95: several strong AI markers together (stock phrases, formulaic structure, no personal detail)
- 0.60-0.85: some AI markers, but not conclusive
- 0.40-0.60: mixed or weak evidence either way
- 0.15-0.40: mostly human traits, but not conclusive
- 0.05-0.15: clear human traits (personal specifics, irregular rhythm, casual voice, typos)

Respond with only a JSON object in this exact form:
{"ai_probability": <number between 0 and 1>, "reasoning": "<one sentence>"}"""

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"], timeout=TIMEOUT_SECONDS)
    return _client


def _unavailable(reason):
    return {"ai_probability": None, "reasoning": reason, "status": "unavailable"}


IMAGE_SYSTEM_PROMPT = """You are an AI-image detector. You cannot see the image. You are given the creator's description of the image and its embedded metadata. Estimate the probability that the image was generated by an AI tool rather than captured or made by a person.

Consider:
- Description phrased like a generator prompt ("hyperrealistic", "8k", "trending on artstation", "cinematic lighting, ultra detailed")
- Scenes that are physically implausible or impossibly perfect
- Metadata that contradicts itself (for example a phone camera model with a square 1024x1024 size, or camera settings with no camera model)
- Concrete, mundane details and consistent camera settings, which point to a real photo or a person's own work

Use the full scale:
- 0.85-0.95: several strong AI indicators together
- 0.60-0.85: some AI indicators, but not conclusive
- 0.40-0.60: mixed or weak evidence either way
- 0.15-0.40: mostly human indicators, but not conclusive
- 0.05-0.15: clear human indicators

Respond with only a JSON object in this exact form:
{"ai_probability": <number between 0 and 1>, "reasoning": "<one sentence>"}"""


def _classify(system_prompt, user_content):
    """Call the model and return a signal dict. Never raises."""
    try:
        completion = _get_client().chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
        )
        data = json.loads(completion.choices[0].message.content)
        prob = float(data["ai_probability"])
    except Exception as exc:
        return _unavailable(f"LLM signal failed: {type(exc).__name__}")

    if prob != prob:  # NaN
        return _unavailable("LLM signal returned NaN")

    return {
        "ai_probability": round(min(MAX_PROB, max(MIN_PROB, prob)), 2),
        "reasoning": str(data.get("reasoning", "")).strip(),
        "status": "ok",
    }


def llm_signal(text):
    """Classify text with the LLM. Returns a dict matching planning.md Section 2."""
    words = text.split()
    if len(words) > MAX_WORDS:
        text = " ".join(words[:MAX_WORDS])
    return _classify(SYSTEM_PROMPT, f"Text to analyze:\n\n{text}")


def llm_image_signal(description, metadata):
    """Judge an image from its description and metadata. Spec: planning.md S2."""
    content = (
        f"Description:\n{description or '(none provided)'}\n\n"
        f"Metadata:\n{json.dumps(metadata or {}, indent=2)}"
    )
    return _classify(IMAGE_SYSTEM_PROMPT, content)
